// flow-typed signature: 0727d939bc2ff5cbe0e185863086e18d
// flow-typed version: <<STUB>>/lodash.bind_v^4.2.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.bind'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.bind' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.bind/index' {
  declare module.exports: $Exports<'lodash.bind'>;
}
declare module 'lodash.bind/index.js' {
  declare module.exports: $Exports<'lodash.bind'>;
}
